import os

RABBITMQ_PORT = os.getenv("RABBITMQ_PORT")
RABBITMQ_MANAGEMENT_PORT = os.getenv("RABBITMQ_MANAGEMENT_PORT")
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")

ELASTICSEARCH_PORT = 9200
ELASTIC_PASSWORD = os.getenv("ELASTIC_PASSWORD", "admin")
ELASTIC_USER = os.getenv("ELASTIC_USER", "elastic")
ELASTIC_HOST = os.getenv("ELASTIC_HOST", "http://elasticsearch:9200")
